apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lms-backend-hpa
  namespace: lms-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lms-backend-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50