apiVersion: v1
kind: Service
metadata:
  name: lms-backend-service
  namespace: lms-namespace
spec:
  type: NodePort
  selector:
    app: lms-backend
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400   # Exposes backend on NodePort 30400→4000