apiVersion: v1
kind: Service
metadata:
  name: lms-frontend-service
  namespace: lms-namespace
spec:
  type: NodePort
  selector:
    app: lms-frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30073   # Exposes frontend on NodePort 30073→5173