apiVersion: v1
kind: Service
metadata:
  name: lms-mongo-express-service
  namespace: lms-namespace
spec:
  type: NodePort
  selector:
    app: lms-mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081   # Exposes mongo-express at NodePort 30081→8081